name: SimpleTimedRank
version: 1.4.5
description: "With this plug-in you can promote or demote a player with a variable rank until a given date. This is very helpful for server owners who want to set a player to a special rank like VIP."
author: Bodyash
website: https://www.spigotmc.org/resources/simpletimedrank.26566

main: me.bodyash.SimpleTimedRank.Main.Main
database: false

commands:
    str:
      help:
        description: Displays the help dialog.
        permissions: simpletimedrank.help
        default: op
        usage: /<command> help
      reload:
        description: Reloads the whole plugin.
        permission: simpletimedrank.reload
        default: op
        usage: /<command> reload
    tempRank:
      description: Promotes a specified player until a given time.
      permissions: simpletimedrank.tempRank
      default: op
      usage: /<command> [PlayerName] [NewRank] [DaysOrMonths] (TimeOfDay) [OldRank]
      aliases: [upRank]
    downRank:
      description: Demotes a Player to his old rank and sets the promotion stats to "expired".
      permission: simpletimedrank.downRank
      default: op
      usage: /<command> [PlayerName]
    timeLeft:
      description: Shows the remaining time until your rank will expire.
      permission: simpletimedrank.timeLeft
      default: op
      usage: /<command> (PlayerName)
      aliases: [daysLeft, dayLeft]