name: SimpleTimedRank
version: 1.0
description: "With this plug-in you can promote or demote a player with a variable rank until a given date. This is very helpful for server owners who want to set a player to a special rank like VIP."
author: Bodyash
website: http://dev.bukkit.org/server-mods/simplepromote/

main: me.bodyash.SimpleTimedRank.Main.Main
database: false

commands:
    sp:
      help:
        description: Displays the help dialog.
        permissions: simpletimepromotion.help
        default: op
        usage: /<command> help
      reload:
        description: Reloads the whole plugin.
        permission: simpletimepromotion.reload
        default: op
        usage: /<command> reload
    tempRank:
      description: Promotes a specified player until a given time.
      permissions: simpletimepromotion.tempRank
      default: op
      usage: /<command> [PlayerName] [NewRank] [Date] (Time) [OldRank]
      aliases: [upRank]
    downRank:
      description: Demotes a Player to his old rank and sets the promotion stats to "expired".
      permission: simpletimepromotion.downRank
      default: op
      usage: /<command> [PlayerName]
    timeLeft:
      description: Shows the remaining time until your rank will expire.
      permission: simpletimepromotion.timeLeft
      default: op
      usage: /<command> (PlayerName)
      aliases: [daysLeft, dayLeft]